---
version: '3'
services:
  dev:
    build:
      context: ./DEV
      dockerfile: Dockerfile
    volumes:
      - 'vlm:/tmp/boxfuse/boxfuse-sample-java-war-hell/target'
  prd:
    build:
      context: ./PRD
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - dev
    volumes:
      - 'vlm:/opt/tomcat/webapps'
      - '~/HmWrk7/context.xml:/opt/tomcat/webapps/manager/META-INF/context.xml'
      - '~/HmWrk7/server.xml:/opt/tomcat/conf/server.xml'
      - '~/HmWrk7/tomcat-users.xml:/opt/tomcat/conf/tomcat-users.xml'
volumes:
  vlm:
...