---
version: '3'
services:
  dev:
    build:
      context: ./DEV
      dockerfile: Dockerfile1
    volumes:
      - 'vol:/usr/koddas/war-web-project/target'
  prd:
    build:
      context: ./PRD
      dockerfile: Dockerfile2
    ports:
      - '8080:8080'
    depends_on:
      - dev
    volumes:
      - 'vol:/opt/tomcat/webapps'
volumes:
  volumeD:
...