---
version: '3.8'
services:
  dev:
    build:
      context: ./DEV #https://github.com/Terion22/Docker_practice2.git
      dockerfile: Dockerfile
    volumes:
      - 'common_volume:/usr/local/src/war-web-project/target/'
#------------------------------------------------------------------------
  prd:
    build:
      context: ./PRD
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - dev
    volumes:
      - 'common_volume:/usr/local/tomcat/webapps/'
volumes:
  common_volume:
...