---
version: '3.8'
services:
  dev:
    build:
      context: ./DEV
      dockerfile: Dockerfile1
    volumes:
      - 'c_vol:/tmp/koddas/war-web-project/target'
  prd:
    build:
      context: ./PRD
      dockerfile: Dockerfile2
    ports:
      - '8080:8080'
    depends_on:
      - dev
    volumes:
      - 'c_vol:/opt/tomcat/webapps'
volumes:
  com_vol:
...