---
version: '3.8'
services:
  dev:
    build:
      context: ./DEV #https://github.com/Terion22/Docker_practice2.git
      dockerfile: Dockerfile
    volumes:
      - common_volume:/home/elshl/superproject/war-web-project/target/

  prd:
    build:
      context: ./PRD
      dockerfile: Dockerfile
    potrs:
      8080:80
    depends_on:
      - dev
    volumes:
      - common volume:/home/elshl/superproject/war-web-project/target/

volumes:
  common volume:
...