---
version: '3.8'
services:
  dev:
    build:
      context: ./DEV
      dockerfile: Dockerfile
    volumes:
      - 'com_vol:/usr/local/src/war-web-project/target/'
  prd:
    build:
      context: ./PRD
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - dev
    volumes:
      - 'com_vol:/opt/tomcat/webapps'
volumes:
  com_vol:
...