---
version: '3'
services:
  dev:
    build:
      context: ./DEV
      dockerfile: Dockerfile
    volumes:
      - 'vlm:/tmp/koddas/war-web-project/target'
  prd:
    build:
      context: ./PRD
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - dev
    volumes:
      - './context.xml:/opt/tomcat/webapps/manager/META-INF/context.xml'
      - './context.xml:/opt/tomcat/webapps/host-manager/META-INF/context.xml'
      - './tomcat-users.xml:/opt/tomcat/conf/tomcat-users.xml'
      - 'vlm:/opt/tomcat/webapps/manager'
volumes:
  vlm:
...