---
version: '3'
services:
  dev:
    build:
      context: ./DEV
      dockerfile: Dockerfile
    volumes:
      - 'c_vol:/tmp/koddas/war-web-project/target'
  prd:
    build:
      context: ./PRD
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - dev
    volumes:
      - 'c_vol:/var/lib/tomcat9/webapps/'
volumes:
  c_vol:
...