---
version: '3'
services:
  dev:
    build:
      context: ./DEV
      dockerfile: Dockerfile
    volumes:
      - 'common_volume:/usr/local/src/war-web-project/target'
  prd:
    build:
      context: ./PRD
      dockerfile: Dockerfile
    ports:
      - '123:123'
    depends_on:
      - dev
    volumes:
      - 'common_volume:/usr/local/tomcat/webapps/'
volumes:
  common_volume:
...