---
version: '3'
services:
  dev:
    build:
      context: ./DEV
      dockerfile: Dockerfile
    volumes:
      - 'c_vol:/tmp/koddas/war-web-project/target'
  prd:
    build:
      context: ./PRD
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - dev
    volumes:
      - 'var/lib/docker/volumes/hmwrk7_c_vol/_data/wwp-1.0.0.war:/opt/tomcat/webapps'
volumes:
  c_vol:
