---
version: '3'
services:
  dev:
    build:
      context: ./dev
      dockerfile: Dockerfile
    volumes:
      - 'common_volume:/usr/local/koddas/war-web-project/target'
  prd:
    build:
      context: ./prd
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - dev
    volumes:
      - 'common_volume:/opt/tomcat/webapps'
volumes:
  common_volume:
...