---
version: '3'
services:
  dev:
    build:
      context: ./DEV
      dockerfile: Dockerfile
    volumes:
      - 'c_vol:/tmp/boxfuse/boxfuse-sample-java-war-hell/target'
  prd:
    build:
      context: ./PRD
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - dev
    volumes:
      - 'c_vol:/usr/local/tomcat/webapps'
volumes:
  c_vol:
